### ISSUE TITLE
Saving/Loading Crash

### ISSUE THREAD

**Issue by MeltageTab** [quxios/Quasi-MV-ABS-Demo#2]
Hello, I'd Like to report a very significant bug.

It seems that whenever you save a game on any map as long as there are enemies present, the came crashes on loading said file, therefore it's more or less impossible to use saving/loading without the game crashing oftenly.

I have managed to reproduce this bug even with a "clean" install of the latest version. All it takes is installing the demo, starting the game, saving it and trying to load the savefile.

I know you'd like a screenshot/video but there's nothing much of help providing that. You can check console output yourself for the detailed info.

I really admire your work and hope to use your plugins in a game I'm working on. Thanks for looking into this in advance.

**Comment by quxios** [comment]
I just tested and can confirm this. Will try to have this fixed in the next update. 
Thanks for letting me know!

**Comment by quxios** [comment]
Just fixed this bug. Grab the latest version of QuasiABS.js and QuasiSight.js
https://github.com/quasixi/Quasi-MV-ABS-Demo/blob/master/js/plugins/QuasiABS.js
https://github.com/quasixi/Quasi-MV-ABS-Demo/blob/master/js/plugins/QuasiSight.js

You can find the notes on what was fixed / changed in this post:
http://forums.rpgmakerweb.com/index.php?/topic/52049-quasi-abs/&page=18#comment-617505
