### ISSUE TITLE
Error when testing new game

### ISSUE THREAD

**Issue by kanzaki1201** [quxios/Quasi-MV-ABS-Demo#4]
Hello Quasi.
I downloaded the demo file and installed according to instructions.
But when I tried to test the game, it came up with error.
My MV version is 1.31.
I am not good at scripting so I don;t know what happened.
Thank you.
![655](https://cloud.githubusercontent.com/assets/6962263/17648079/d6337064-623b-11e6-8968-ad5b894d0e35.png)

**Comment by kanzaki1201** [comment]
I saw your twitter and replaced index.html
But new error showed
![657](https://cloud.githubusercontent.com/assets/6962263/17648299/cb9406b8-6241-11e6-9d39-ce732847a7b2.png)

**Comment by smulholland2** [comment]
Thats being caused by the Sight plugin. Just set it to "off" and you can test the ABS.

**Comment by quxios** [comment]
All you need to do is open the plugin manager and Right Click > Refresh on the QuasiSight plugin.
- Deleted the plugins.js file. Now you need to manually add in all the plugins / configure them. Old plugins.js hadn't been updated which is what cases that error ( can easily update with Right Click > Refresh )
