### ISSUE TITLE
Can i make enemy(event) target another enemy (event)?

### ISSUE THREAD

**Issue by sttifer** [quxios/Quasi-MV-ABS-Demo#6]

**Comment by quxios** [comment]
Haven't tested it, but ideally these should work:

First, make sure both enemies are on different teams using the <team:X> notetag in the enemy notes.

1st method:
use a script call to force agro from one enemy to the other, ex:
~~~js
$gameMap.event(EVENT1 ID).addAgro(EVENT2 ID);
~~~
Then let the AI take over.

2nd method:
use a script call to make them attack eachother:
~~~js
$gameMap.event(EVENT1 ID).useSkill(SKILL ID);
~~~
Remember to make the event face the target event so it uses the skill in the correct direction

**Comment by quxios** [comment]
Just realized this is for QuasiABS, If you're referring to QABS then that's the solution if not then I'm sorry but QuasiABS is no longer supported.

**Comment by sttifer** [comment]
Cool, thanks, that work it! But i make two enemies <team:A> and two enemies <team:B>. When a enemy <team:A> move and collide with <team:A>, they attack each other but they are in the same team. :/
